import {ArchiveDocumentary} from './ArchiveDocumentary';
import type {ArchiveData} from './types';

const showcaseData: ArchiveData = {
  title: 'Historical Map Engine Showcase',
  fps: 30,
  duration: 24,
  audio: '',
  renderOptions: {
    showSubtitles: true,
    showArchiveOverlay: true,
    showDocumentHighlights: true,
    showKineticMaps: true,
    enableVisualSfx: false,
  },
  captions: [
    {start: 0.3, end: 5.5, text: 'Territories appear as geographic regions—not random pins.'},
    {start: 6.3, end: 11.5, text: 'Borders can expand, contract, divide, or disappear with the narration.'},
    {start: 12.3, end: 17.5, text: 'Campaign routes draw themselves across the historical landscape.'},
    {start: 18.3, end: 23.5, text: 'A person’s journey combines camera travel, a dashed route, and a moving marker.'},
  ],
  scenes: [
    {
      index: 1,
      text: 'At its height, the Byzantine Empire controlled the eastern Mediterranean.',
      prompt: '',
      image: '',
      start: 0,
      end: 6,
      visualCueStart: 0,
      mode: 'map',
      label: 'TERRITORIAL EXTENT',
      visualText: 'THE BYZANTINE EMPIRE',
      dateHint: '565',
      motion: 'slow_push',
      accent: 'kinetic_map',
      graphic: 'kinetic_map',
      mapLabel: 'BYZANTINE EMPIRE',
      historicalMap: {
        mode: 'territory',
        title: 'The Byzantine Empire at its height',
        subtitle: 'Eastern Mediterranean influence under Justinian I',
        year: '565',
        accuracy: 'approximate',
        referenceQuery: 'Byzantine Empire 565 map Justinian territorial extent',
        camera: {center: [18, 37], zoom: 3.2, fromZoom: 2.65},
        places: [
          {label: 'Constantinople', coordinates: [28.97, 41.01], labelPosition: 'right'},
          {label: 'Rome', coordinates: [12.5, 41.9], importance: 'secondary', labelPosition: 'above'},
          {label: 'Carthage', coordinates: [10.33, 36.85], importance: 'secondary', labelPosition: 'below'},
        ],
        territories: [
          {
            id: 'byzantine-565',
            name: 'Byzantine Empire',
            color: '#59445f',
            labelAt: [24, 37],
            polygons: [[
              [-9, 36], [-5, 43], [8, 45], [15, 42], [18, 46], [29, 48],
              [41, 45], [43, 38], [36, 31], [35, 22], [29, 21], [27, 31],
              [20, 33], [15, 37], [10, 35], [5, 36], [-2, 35],
            ]],
          },
        ],
      },
    },
    {
      index: 2,
      text: 'The western empire collapsed while the eastern empire survived.',
      prompt: '',
      image: '',
      start: 6,
      end: 12,
      visualCueStart: 6,
      mode: 'map',
      label: 'BORDERS IN MOTION',
      visualText: 'THE DIVIDED ROMAN WORLD',
      dateHint: '395–476',
      motion: 'drift',
      accent: 'kinetic_map',
      graphic: 'kinetic_map',
      mapLabel: 'ROMAN DIVISION',
      historicalMap: {
        mode: 'transition',
        title: 'The Roman world divides',
        subtitle: 'Western contraction and eastern continuity',
        year: '476',
        accuracy: 'approximate',
        referenceQuery: 'Western Eastern Roman Empire 395 476 historical map',
        camera: {center: [15, 39], zoom: 3.15, fromZoom: 2.72},
        places: [
          {label: 'Rome', coordinates: [12.5, 41.9], labelPosition: 'above'},
          {label: 'Constantinople', coordinates: [28.97, 41.01], labelPosition: 'right'},
        ],
        territories: [
          {
            id: 'western-rome',
            name: 'Western Roman Empire',
            color: '#82433d',
            labelAt: [0, 45],
            previousPolygons: [[
              [-10, 36], [-8, 53], [15, 52], [19, 46], [16, 37], [9, 31], [-3, 31],
            ]],
            polygons: [[
              [7, 40], [14, 46], [17, 45], [16, 38], [11, 37],
            ]],
          },
          {
            id: 'eastern-rome',
            name: 'Eastern Roman Empire',
            color: '#55455f',
            labelAt: [33, 35],
            previousPolygons: [[
              [16, 37], [19, 46], [38, 47], [43, 36], [35, 28], [27, 31],
            ]],
            polygons: [[
              [18, 36], [20, 45], [40, 46], [43, 36], [35, 28], [27, 31],
            ]],
          },
        ],
      },
    },
    {
      index: 3,
      text: 'Armies moved through Constantinople and Anatolia toward Antioch and Jerusalem.',
      prompt: '',
      image: '',
      start: 12,
      end: 18,
      visualCueStart: 12,
      mode: 'map',
      label: 'CAMPAIGN MAP',
      visualText: 'ROUTES INTO THE LEVANT',
      dateHint: '1097–1099',
      motion: 'pan_right',
      accent: 'kinetic_map',
      graphic: 'kinetic_map',
      mapLabel: 'FIRST CRUSADE',
      historicalMap: {
        mode: 'campaign',
        title: 'Routes into the Levant',
        subtitle: 'Multiple forces converge through Anatolia',
        year: '1097',
        accuracy: 'approximate',
        referenceQuery: 'First Crusade campaign routes Constantinople Antioch Jerusalem map',
        camera: {center: [29, 37], zoom: 5.2, fromCenter: [24, 41], fromZoom: 4.1},
        places: [
          {label: 'Constantinople', coordinates: [28.97, 41.01], labelPosition: 'above'},
          {label: 'Antioch', coordinates: [36.16, 36.2], labelPosition: 'right'},
          {label: 'Jerusalem', coordinates: [35.21, 31.77], labelPosition: 'below'},
        ],
        territories: [
          {
            id: 'byzantine-anatolia',
            name: 'Byzantine Empire',
            color: '#5a4861',
            countries: ['Greece', 'Turkey'],
            labelAt: [24, 36.8],
          },
        ],
        routes: [
          {
            id: 'northern-route',
            points: [[16, 48], [23, 45], [28.97, 41.01], [32, 39], [36.16, 36.2]],
            color: '#a84d42',
            startAt: 0.08,
            endAt: 0.69,
          },
          {
            id: 'southern-route',
            points: [[12, 44], [21, 42], [28.97, 41.01], [30, 37], [35.21, 31.77]],
            color: '#b38d46',
            startAt: 0.2,
            endAt: 0.82,
          },
          {
            id: 'eastern-route',
            points: [[43, 43], [39, 40], [36.16, 36.2]],
            color: '#526b78',
            startAt: 0.32,
            endAt: 0.75,
          },
        ],
      },
    },
    {
      index: 4,
      text: 'According to tradition, Byzas sailed from Megara to the Bosporus and founded Byzantium.',
      prompt: '',
      image: '',
      start: 18,
      end: 24,
      visualCueStart: 18,
      mode: 'map',
      label: 'GEOGRAPHIC JOURNEY',
      visualText: 'FROM MEGARA TO BYZANTIUM',
      dateHint: '7TH CENTURY BCE',
      motion: 'pull',
      accent: 'kinetic_map',
      graphic: 'kinetic_map',
      mapLabel: 'BYZAS',
      historicalMap: {
        mode: 'journey',
        title: 'The traditional voyage of Byzas',
        subtitle: 'Megara to the Bosporus',
        year: '667 BCE',
        accuracy: 'approximate',
        referenceQuery: 'Byzas Megara Byzantium voyage historical map',
        camera: {center: [26.3, 39.4], zoom: 23, fromCenter: [23.4, 38], fromZoom: 26},
        places: [
          {label: 'Megara', coordinates: [23.34, 37.99], labelPosition: 'left'},
          {label: 'Byzantium', coordinates: [28.97, 41.01], labelPosition: 'right'},
        ],
        routes: [
          {
            id: 'byzas-voyage',
            label: 'Byzas',
            points: [[23.34, 37.99], [24.8, 37.4], [26.2, 38.2], [27.3, 39.5], [28.97, 41.01]],
            color: '#9f4d43',
            dashed: true,
            startAt: 0.08,
            endAt: 0.76,
          },
        ],
        portraitLabel: 'Byzas · Founder in tradition',
      },
    },
  ],
};

export const UpgradeShowcase = () => <ArchiveDocumentary data={showcaseData} />;
